language: python
# Python releases to test
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
# Django releases
env:
  - DJANGO_VERSION=Django==1.3.5
  - DJANGO_VERSION=Django==1.4.3
  # 1.5 release candidate
  - DJANGO_VERSION=git+git://github.com/django/django.git@f23d3ce8d47cc3ec58cb7fb1b32d3d3237c025f5
# Exclude some Django releases depending on Python version
matrix:
  exclude:
    - python: 3.2
      env: DJANGO_VERSION=Django==1.3.5
    - python: 3.2
      env: DJANGO_VERSION=Django==1.4.3
    - python: 2.5
      env: DJANGO_VERSION=git+git://github.com/django/django.git@f23d3ce8d47cc3ec58cb7fb1b32d3d3237c025f5
install:
  - pip install --use-mirrors $DJANGO_VERSION
  - python setup.py install
script: make test
notifications:
  email:
    on_success: never
    on_failure: change
