language: python
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - DJANGO_VERSION=Django==1.8.8
  - DJANGO_VERSION=Django==1.9.1
install:
  - pip install -q --use-mirrors $DJANGO_VERSION
  - python setup.py install -q
script: make test
notifications:
  email:
    on_success: never
    on_failure: change
