language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
env:
  - DJANGO_VERSION=1.3.5
  - DJANGO_VERSION=1.4.3
script: make test
